2024-07-04 17:18:44,401 [INFO] root tankworker.py:153	Log file created
2024-07-04 17:18:44,402 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 17:18:44,402 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 17:18:44,402 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 17:18:44,413 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_17-18-44.350767
2024-07-04 17:18:44,415 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 17:18:44,415 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 17:18:44,416 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 17:18:44,416 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 17:18:44,416 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 17:18:44,417 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 17:18:44,417 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 17:18:44,417 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 17:18:44,420 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 17:18:44,420 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 17:18:44,421 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 17:18:44,421 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 17:18:44,421 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 17:18:44,421 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 17:18:44,422 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 17:18:44,422 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 17:18:44,422 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 17:18:44,422 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 17:18:45,456 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:18:48,565 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:18:48,565 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:18:49,234 [WARNING] root tankworker.py:118	Interrupting
2024-07-04 17:18:49,236 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'KeyboardInterrupt'>: 
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 579, in resolve
    self.__test(family, (parsed_ip, port))

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 593, in __test
    test_sock.connect(sa)

2024-07-04 17:18:49,238 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 17:18:49,238 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_d2pd46cr.lock
2024-07-04 17:18:49,248 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_17-18-44.350767
2024-07-04 17:18:49,248 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 17:18:49,250 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-44.350767/answ_mo6fn6_t.log
2024-07-04 17:18:49,251 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-44.350767/phout_c_b88dtf.log
2024-07-04 17:18:49,253 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-44.350767/phantom_stat_xzdc4wpr.log
2024-07-04 17:18:49,254 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-44.350767/phantom_qyr__l2d.log
