2024-07-04 17:09:40,563 [INFO] root tankworker.py:153	Log file created
2024-07-04 17:09:40,563 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 17:09:40,563 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 17:09:40,563 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 17:09:40,574 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_17-09-40.503482
2024-07-04 17:09:40,576 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 17:09:40,576 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 17:09:40,577 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 17:09:40,577 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 17:09:40,578 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 17:09:40,578 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 17:09:40,578 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 17:09:40,579 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 17:09:40,581 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 17:09:40,581 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 17:09:40,582 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 17:09:40,582 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 17:09:40,582 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 17:09:40,583 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 17:09:40,583 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 17:09:40,583 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 17:09:40,584 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 17:09:40,584 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 17:09:41,633 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:09:44,768 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:09:44,770 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:09:46,351 [WARNING] root tankworker.py:118	Interrupting
2024-07-04 17:09:46,351 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'KeyboardInterrupt'>: 
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 579, in resolve
    self.__test(family, (parsed_ip, port))

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 593, in __test
    test_sock.connect(sa)

2024-07-04 17:09:46,352 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 17:09:46,352 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_caysgy4y.lock
2024-07-04 17:09:46,359 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_17-09-40.503482
2024-07-04 17:09:46,360 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 17:09:46,361 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-09-40.503482/answ_a49i_cd8.log
2024-07-04 17:09:46,363 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-09-40.503482/phout_h4igsy9v.log
2024-07-04 17:09:46,364 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-09-40.503482/phantom_stat_rhv0kmid.log
2024-07-04 17:09:46,365 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-09-40.503482/phantom_dzxzuqhl.log
