2024-06-28 08:48:34,427 [INFO] root tankworker.py:153	Log file created
2024-06-28 08:48:34,427 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-06-28 08:48:34,428 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-06-28 08:48:34,428 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-06-28 08:48:34,438 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-06-28_08-48-34.375202
2024-06-28 08:48:34,440 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-06-28 08:48:34,441 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-06-28 08:48:34,441 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-06-28 08:48:34,441 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-06-28 08:48:34,442 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-06-28 08:48:34,442 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-06-28 08:48:34,443 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-06-28 08:48:34,443 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-06-28 08:48:34,447 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-06-28 08:48:34,448 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-06-28 08:48:34,448 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-06-28 08:48:34,448 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-06-28 08:48:34,449 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-06-28 08:48:34,449 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-06-28 08:48:34,450 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-06-28 08:48:34,450 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-06-28 08:48:34,450 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-06-28 08:48:34,451 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-06-28 08:48:35,483 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 127.0.0.1 and port 5000
2024-06-28 08:48:35,484 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [127.0.0.1]:5000
2024-06-28 08:48:35,484 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 127.0.0.1 and port 5000
2024-06-28 08:48:35,484 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [127.0.0.1]:5000
2024-06-28 08:48:35,485 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 127.0.0.1 and port 5000
2024-06-28 08:48:35,485 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [127.0.0.1]:5000
2024-06-28 08:48:35,486 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'RuntimeError'>: All connection attempts failed for 127.0.0.1, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 587, in resolve
    raise RuntimeError(msg % address_str)

2024-06-28 08:48:35,486 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-06-28 08:48:35,487 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_2peaf2vo.lock
2024-06-28 08:48:35,493 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-06-28_08-48-34.375202
2024-06-28 08:48:35,493 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-06-28 08:48:35,495 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-06-28_08-48-34.375202/answ_bandim57.log
2024-06-28 08:48:35,498 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-06-28_08-48-34.375202/phout_csehq5ic.log
2024-06-28 08:48:35,500 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-06-28_08-48-34.375202/phantom_stat_dpg1potl.log
2024-06-28 08:48:35,502 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-06-28_08-48-34.375202/phantom_dsyeii02.log
