2024-07-04 15:06:12,262 [INFO] root tankworker.py:153	Log file created
2024-07-04 15:06:12,262 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 15:06:12,262 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 15:06:12,263 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 15:06:12,273 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_15-06-12.209675
2024-07-04 15:06:12,274 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 15:06:12,275 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 15:06:12,275 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 15:06:12,275 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 15:06:12,276 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 15:06:12,276 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 15:06:12,276 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 15:06:12,277 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 15:06:12,279 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 15:06:12,279 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 15:06:12,280 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 15:06:12,280 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 15:06:12,280 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 15:06:12,280 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 15:06:12,281 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 15:06:12,281 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 15:06:12,281 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 15:06:12,282 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 15:06:13,326 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 5000
2024-07-04 15:06:15,375 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:5000
2024-07-04 15:06:15,376 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 5000
2024-07-04 15:06:17,422 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:5000
2024-07-04 15:06:17,424 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 5000
2024-07-04 15:06:19,476 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:5000
2024-07-04 15:06:19,480 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 587, in resolve
    raise RuntimeError(msg % address_str)

2024-07-04 15:06:19,481 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 15:06:19,481 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_788h0za1.lock
2024-07-04 15:06:19,487 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_15-06-12.209675
2024-07-04 15:06:19,488 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 15:06:19,489 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_15-06-12.209675/answ_s_q_a7lf.log
2024-07-04 15:06:19,491 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_15-06-12.209675/phout_g_8wq1ru.log
2024-07-04 15:06:19,492 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_15-06-12.209675/phantom_stat_awlmf520.log
2024-07-04 15:06:19,493 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_15-06-12.209675/phantom_wk4tkn9q.log
